# Generated by Django 4.2.6 on 2023-11-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('release_date', models.DateTimeField(null=True)),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(verbose_name=models.CharField(max_length=50))),
            ],
        ),
    ]
